name: Python Test

on:
    schedule:
      - cron: '*/15 * * * *'  # Run every 15 minutes
    push:
      branches:
        - main
        - development  # Add the second branch you want to monitor

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Choose the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python -m pytest test/

      - name: Run Black
        run: black *.py

      - name: Run Pylint
        run: |
          pylint --disable=R,C,E1120 *.py
        continue-on-error: true

      - name: Display Pylint results
        run: |
          pylint --disable=R,C,E1120 *.py
        continue-on-error: true
        

